name: environment
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas-datareader>=0.5.0
  - matplotlib>=2.1.1
  - astropy>=3.2.2
  - numpy>=1.17.3
  - pandas>=0.25.2
  - scipy>=1.3.1
  - ipywidgets>=7.5.1
  - MontagePy